export {default as Login} from "./Login"
export {default as Signup} from "./Signup"
export {default as Home} from "./Home"
export {default as ForgotPassword} from "./ForgotPassword"
export {default as ResetPassword} from "./ResetPassword"
export {default as NotFoundPage} from "./404"